name: tudo_client
description: A simple to-do app
version: 1.0.0
homepage: https://github.com/cachapa/tudo_client

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0

  hive_crdt: ^2.0.2
  http: ^0.13.3
  web_socket_channel: ^2.1.0

  clipboard: ^0.1.2+8
  device_info_plus: ^2.1.0
  flutter_barcode_scanner: ^2.0.0
  implicitly_animated_reorderable_list: ^0.4.1
  path_provider: ^2.0.4
  qr_flutter: ^4.0.0
  share_plus: ^2.1.4
  uni_links: ^0.5.1
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: WaitingfortheSunrise
      fonts:
        - asset: assets/fonts/WaitingfortheSunrise-Regular.ttf
