name: tudo_client
description: A simple to-do app
version: 1.0.0
homepage: https://github.com/cachapa/tudo_client

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.2

  hive: ^2.0.4
  http: ^0.13.4
  web_socket_channel: ^2.1.0

  rxdart: ^0.27.2
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.1.0
  # Required for Android because UPSERTs are not supported there
  sqlite3_flutter_libs: ^0.5.1

  clipboard: ^0.1.2+8
  device_info_plus: ^3.2.1
  flutter_barcode_scanner: ^2.0.0
  implicitly_animated_reorderable_list: ^0.4.2
  package_info_plus: ^1.3.0
  path_provider: ^2.0.8
  qr_flutter: ^4.0.0
  share_plus: ^3.0.4
  uni_links: ^0.5.1
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/
