name: tudo_client
description: A simple to-do app
version: 1.0.0
homepage: https://github.com/cachapa/tudo_client

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  crypto: ^2.1.5
  provider: ^4.0.0

  crdt: ^2.2.1
  hive: ^1.4.0

  http: ^0.12.0+3
  web_socket_channel: ^1.1.0

  clipboard: ^0.1.2+8
  implicitly_animated_reorderable_list: 0.4.0-dev+1 #^0.3.2
  path_provider: ^1.6.0
  qr_flutter: ^3.1.0
  share: ^0.6.5+3
  uni_links: ^0.4.0
  flutter_slidable: ^0.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: WaitingfortheSunrise
      fonts:
        - asset: assets/fonts/WaitingfortheSunrise-Regular.ttf
