name: tudo_app
description: A simple to-do app
version: 0.0.0
homepage: https://github.com/cachapa/tudo
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  hive: ^2.2.2
  http: ^0.13.4
  web_socket_channel: ^2.2.0

  provider: ^6.0.3
  rxdart: ^0.27.4
  sqflite: ^2.0.2
  sqflite_common_ffi: ^2.1.1
  # Required for Android and iOS because UPSERTs are only supported on very recent OS versions
  sqlite3_flutter_libs: ^0.5.7

  clipboard: ^0.1.2+8
  device_info_plus: ^3.2.4
  flutter_barcode_scanner: ^2.0.0
  implicitly_animated_reorderable_list:
    git: https://github.com/storyark-app/implicitly_animated_reorderable_list.git
  package_info_plus: ^1.4.2
  path_provider: ^2.0.11
  qr_flutter: ^4.0.0
  share_plus: ^4.0.8
  uni_links: ^0.5.1
  uuid: ^3.0.6
  url_launcher: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  flutter_lints: any

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
