name: tudo_app
description: A simple to-do app
version: 1.0.0
homepage: https://github.com/cachapa/tudo

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  hive: ^2.0.5
  http: ^0.13.4
  web_socket_channel: ^2.1.0

  provider: ^6.0.2
  rxdart: ^0.27.2
  sqflite: ^2.0.2
  sqflite_common_ffi: ^2.1.0+1
  # Required for Android and iOS because UPSERTs are only supported on very recent OS versions
  sqlite3_flutter_libs: ^0.5.3

  clipboard: ^0.1.2+8
  device_info_plus: ^3.2.1
  flutter_barcode_scanner: ^2.0.0
  implicitly_animated_reorderable_list: ^0.4.2
  package_info_plus: ^1.3.0
  path_provider: ^2.0.8
  qr_flutter: ^4.0.0
  share_plus: ^3.0.4
  uni_links: ^0.5.1
  uuid: ^3.0.5
  url_launcher: ^6.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  flutter_lints: any

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
