name: tudo_server
description: Server counterpart to the tudo app
version: 1.0.0
homepage: https://github.com/cachapa/tudo

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  args: ^2.0.0
  http: ^0.13.0
  shelf: ^1.2.0
  shelf_router: ^1.1.2
  shelf_web_socket: ^1.0.1
  web_socket_channel: ^2.1.0
  uuid: ^3.0.5

  rxdart: ^0.27.2
  sqflite_common_ffi: ^2.1.0

dev_dependencies:
  lints: any
  test: any
