name: Quality Gate

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'

      - name: Verify code formatting
        run: dart format --output none --set-exit-if-changed .
      - name: Static code analysis
        run: flutter analyze .
      - name: Run tests
        run: flutter test
